### ISSUE TITLE
Spectral type string variety

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#100]
Do we want to require a specific format to the spectral types in the schema? e.g. first char should be in M,L,T,Y (or any letter perhaps); second char should be inclusively between 0-9.  
To stop certain structures like "sdM0" or ">M10V".

**Comment by kelle** [comment]
I am ok with spectral type string being whatever it is, with whatever prefix's and suffix's the author's so choose. In PR #94 , I am modifying the schema so there's a spectral type code which can be used for querying. E.g., 0 = M0, 10=L0, etc.

**Comment by kelle** [comment]
@Will-Cooper , is your concern addressed by the [Spectral Type tables doc](https://github.com/SIMPLE-AstroDB/SIMPLE-db/blob/main/documentation/SpectralTypes.md)?  Maybe we should add more text there to say that `spectral_type_string` can be whatever, but `spectral_type_code` is standardized?

**Comment by Will-Cooper** [comment]
Sure, do we also want ```spectral_type_code``` to be searchable on? Would be nice to search ```spectral_type_string``` but understand that could get complex? I personally use 60=M0, 70=L0 but as long as the standardisation is listed as it is, don't think anyone can complain!

**Comment by kelle** [comment]
I think this is worth discussing...60 = M0 vs 0 = M0. Can you say a little bit about why you chose to start with 60?

**Comment by Will-Cooper** [comment]
It's more inclusive of the MS stars, useful if you're dealing with multiple systems and dumping both primaries and companions in the same table and want an automated system to create the numerical types. i.e. OBAFGKMLTY = 0,10,20,30,40,50,60,70,80,90

**Comment by kelle** [comment]
Any other thoughts on this? @NiallWhiteford ? @cfontanive ? @aburgasser ?  (We need to decide before we can merge #112.)

**Comment by cfontanive** [comment]
If we're not including any objects earlier than ~mid-M, I would vote for MLTY=0,10,20,30 which is typically used in substellar contexts. We may have some comments about binarity for companion objects somewhere (?), but unless the primaries are themselves substellar, they won't have their own entry in the database, right? So this should not be a problem.
I also agree with the spectral type string being allowed to be whatever ('sd', '>', a range...) and for queries to be made based on the spectral type code (M6, sdM6, >M6, M6-7 would all be 6 for example).

**Comment by kelle** [comment]
One thing I just thought of: if we go with the 0=O, 60=M0, it's higher probability that our database will be more compatible with other databases. @dr-rodriguez , is there some VO standard for this. (I doubt it, but thought I would ask. Maybe we should propose one!)

**Comment by Will-Cooper** [comment]
The only thing I can find online is the UCD keyword of ```src.spType```, which is the MK spectral type as a string -- I don't think there's a vigorous standard anywhere... Perhaps a twitter poll? Eric Mamajek as well might be a good person to ask?

**Comment by kelle** [comment]
In interest of the future possibility of ingesting data on primary stars, we've decided to go with OBAFGKMLTY = 0,10,20,30,40,50,60,70,80,90. So M0=60. (And the docs need to be updated.)
