### ISSUE TITLE
Ingestion of sources not in Simbad

### ISSUE THREAD

**Issue by cfontanive** [SIMPLE-AstroDB/SIMPLE-db#105]
How do we check whether a source already exists in the database if it is not in Simbad? (e.g. WISEA J030237.52-581740.3 in the Y dwarf table)

**Comment by kelle** [comment]
It looks like you took care of this issue in your [Y_dwarf_source_ingest.py](https://github.com/SIMPLE-AstroDB/SIMPLE-db/blob/main/scripts/ingests/Y_dwarf_source_ingest.py) script. We'll eventually get to using that method in the ingesting ATLAS script as well.

Do we need to keep this issue open or was there something else we wanted to do here?

**Comment by cfontanive** [comment]
No, I am currently ignoring this source in my script, which is why I started this issue. I currently use Simbad to check whether a source is already in the database or not, but we need a way to do this for cases of sources that do not exist in Simbad (not just under a different name).

**Comment by kelle** [comment]
Ah, i see, you're ignoring it with `data_start=2` on line 16? 

So we need to incorporate the Simbad search thing we've added to `ingest_ATLAS_will_work.py`, currently a WIP in #106 . I think you can copy and paste lines 31-63 and then loop over `resolved_name` instead of `Ydwarfs['source']`. Sound like a plan?

**Comment by kelle** [comment]
nope, nope, not a plan at all. We need to fill out the final `else` in that script (line 62-63). (And probably turn it into a function!!). I think we need to make a 2nd empty list which gets populated. Maybe we make a  `not_in_simbad` list to partner with `resolved_name`. So if both the identifier and coord searches failed, the `ATLAS['Name']` gets appended to `not_in_simbad`.

**Comment by cfontanive** [comment]
Yes that source is the first one in my list, so I'm currently skipping it.
This won't help – that Simbad loop was made to identify the Simbad names of sources that were not recognised in Simbad with the names from the ATLAS list. The source listed above does not exist in Simbad at all, so we currently have no way to check whether it is already in the database.

**Comment by cfontanive** [comment]
> nope, nope, not a plan at all. We need to fill out the final `else` in that script (line 62-63). (And probably turn it into a function!!). I think we need to make a 2nd empty list which gets populated. Maybe we make a `not_in_simbad` list to partner with `resolved_name`. So if both the identifier and coord searches failed, the `ATLAS['Name']` gets appended to `not_in_simbad`.

Yes, I agree that you need something like this. But we also still need to figure out how to then deal with those as we need to way to check whether the source is already in SIMPLE, and if so, under what name.

**Comment by kelle** [comment]
I'm not exactly sure of the best way to code this but I think the idea is:
```
for i,name in enumerate(Ydwarfs['source']):
```
If `name`  is a `not_in_simbad` object, then test `db.search_object(name,resolve_simbad=False)`. if that also fails, then it goes to the final else and `missing_sources.append(i)`

```
	if len(db.search_object(name,resolve_simbad=True)) != 0:
		existing_sources.append(i)
		db_names.append(db.search_object(name,resolve_simbad=True)[0].source)
	else:
		missing_sources.append(i)
		db_names.append(Ydwarfs['source'][i])
```

at some point, we should probably also search for matches based on coordinates, but I think we can save that for another day.

**Comment by cfontanive** [comment]
I think that's a bit dangerous, as we risk adding sources that are already in the database but under a different name... I also can't find any method in astrodbkit2 to search for objects in the the database based on coordinates.

**Comment by dr-rodriguez** [comment]
So this is one of the reasons we created the Names table and enforce the population of it. The user is expected to fill in that information for new sources so that they can be matched (search_object checks that table and the Sources table) regardless of whether they are in Simbad or not.

As for searching by coordinates: there is an open ticket for that in AstrodbKit2 https://github.com/dr-rodriguez/AstrodbKit2/issues/3 that I haven't had a chance to work on yet. In the meantime, this is something one can run manually since the DB table is not that big.

**Comment by kelle** [comment]
I will try to implement this now that `query_region` method exists in Astrodbkit2. https://astrodbkit2.readthedocs.io/en/latest/#region-spatial-search

**Comment by kelle** [comment]
This functionality now exists. I'll try to ingest that one Y dwarf soon.
