### ISSUE TITLE
Brown Dwarf Spectral libraries E. Manjavacas

### ISSUE THREAD

**Issue by elenamanjavacas** [SIMPLE-AstroDB/SIMPLE-db#111]
The Brown Dwarf Libraries described here can be found here:
[https://github.com/elenamanjavacas/spectral_libraries](https://github.com/elenamanjavacas/spectral_libraries)

- [x] VLT/ISAAC Young Brown Dwarf NIR Library [http://adsabs.net/abs/2014A&A...564A..55M](url):  Medium-resolution (R ~ 1500-1700) near-infrared (1.1-2.5 μm) spectra of seven young M9.5-L3 dwarfs.

- [x] VLT/XShooter optical+NIR [http://adsabs.net/abs/2016MNRAS.455.1341M](http://adsabs.net/abs/2016MNRAS.455.1341M): 0.6-2.7 micron, medium-resolution spectra of 22 L3-T7 brown dwarfs of different surface gravities. Some of them catalogued as binary candidates.

- [x] HST/WFC3+G141 NIR Brown Dwarf Spectra [http://adsabs.net/abs/2019AJ....157..101M](http://adsabs.net/abs/2019AJ....157..101M):  high signal-to-noise spectral library (1.10-1.69 μm) of the thermal emission of 76 brown dwarfs and hot Jupiters. The near-infrared spectral types of these objects range from L4 to Y1, and a variety of surface gravities. Uniform data set of a broad range of ultracool atmospheres, allowing large-scale comparative studies and providing an HST legacy spectral library.

- [x] VLT/XShooter optical+NIR Age-benchmark Brown Dwarfs  [http://adsabs.net/abs/2020MNRAS.491.5925M](http://adsabs.net/abs/2020MNRAS.491.5925M): 0.6-2.5 micron spectra of benchmark M6-L3 sample of brown dwarf members of Chamaeleon I (~2 Myr), Upper Scorpius (5-10 Myr), the Pleiades (132 ± 27 Myr) and Praesepe (590-790 Myr) with well-constrained ages and similar metallicities.

**Comment by kelle** [comment]
These are great compilations but in order to ingest, we need one URL per spectrum. @elenamanjavacas , do you want to try and work on that (maybe with your institutions library or institutional repository)? Or we can just upload them to our AWS drive. Let us know what you prefer.

**Comment by SherelynA** [comment]
[Manja_spectra4.csv](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/7637095/Manja_spectra4.csv)

**Comment by kelle** [comment]
VLT/ISAAC Young Brown Dwarf NIR Library completed in PR #213.

**Comment by kelle** [comment]
Manj16 done in PR #226.

Looks like Manj19 has a downloadable ASCII table we can start with in Table 12: 
https://iopscience.iop.org/article/10.3847/1538-3881/aaf88f#ajaaf88ft12

**Comment by kelle** [comment]
HST/WFC3 spectra now uploaded to https://bdnyc.s3.amazonaws.com/WFC3/. For example: 
https://bdnyc.s3.amazonaws.com/WFC3/CD-3527B.csv

**Comment by kelle** [comment]
VLT/Xshooter data uploaded to https://bdnyc.s3.amazonaws.com/XShooter/. For example: https://bdnyc.s3.amazonaws.com/XShooter/2M11085497-763240.txt
