### ISSUE TITLE
Recent PRs duplicating all JSON files

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#114]
recent PRs which modify the database include duplicate copies of all the JSON files for all sources and not just the ones which were modified.

**Comment by kelle** [comment]
I suspect it's something about the order in which we did things. Maybe `db.save` could just be modified to say, "Wrote # of JSON files". That way, we'll get a heads up when it's written too many and can fix it before committing.

**Comment by dr-rodriguez** [comment]
The way `db.save_database` works is that it is supposed to clear all output in the directory before writing out the json files. And when it does output files it uses `open(name, 'w')` which is supposed to overwrite files with the same name. 
I thought it might have to do with the way the ingests scripts are using `../../data` as opposed to `data` but I was able to run both ways without encountering duplicates.

My suspicion is that this has to do more with git than with astrodbkit2, so I searched for duplication issues with github and  found these two interesting links:
https://stackoverflow.com/questions/62385234/git-keeps-duplicating-files-and-appending-2-at-end-of-filename
https://stackoverflow.com/questions/59308049/icloud-drive-desktop-sync-vs-git-deleted-files-reappear-and-duplicates-with-n

The problem appears to be the use of iCloud, Dropbox, Drive, and similar file syncing services. If you have these set up in the directory you have the database (or any github repo) in, it will get confused when you pull, switch branches, or save the database. While iCloud is working out its confusion it will have duplicate entries with that extra number which as we realized can be inadvertently committed and pushed. I don't have this repo in my synced folders which is likely why I haven't encountered this.

I guess the confirmation can come from @cfontanive and @NiallWhiteford : are you both using iCloud or similar services and do you have the SIMPLE repo in directories tracked by that? If so, that could be the cause and we will want to alert users that this can be a problem. My recommendation would be to move SIMPLE repo out of Documents or whatever is being synced and/or configure your software to ignore that directory.

**Comment by cfontanive** [comment]
Yes my SIMPLE repo is indeed in a directory that is synced using iCloud so the issue must come from there.

**Comment by NiallWhiteford** [comment]
Same here. my repo in is my icloud docs.

**Comment by Will-Cooper** [comment]
Is this still active?

**Comment by kelle** [comment]
I think we've "solved" this issue.
