### ISSUE TITLE
Where do we store spectra?

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#132]
As the title reads. Need an area that the website can draw from when we get to that to get spectra as in https://github.com/SIMPLE-AstroDB/SIMPLE-web/issues/24.

**Comment by kelle** [comment]
The BDNYC database used Amazon Web Services. We’ve never been billed. I vote that we continue using that (using the BDNYC account) until it no longer becomes sustainable. 

Long term, we should encourage folks to use their institutional repositories to get permalinks for each spectrum.

**Comment by Will-Cooper** [comment]
Sure, I guess also define "permalink" as sometimes people remove things as they move between insitutions etc? We probably want our own managed storage which will be permeant as long as the project is running!

**Comment by kelle** [comment]
Here is the link:
https://s3.console.aws.amazon.com/s3/buckets/bdnyc?region=us-east-1&tab=objects#

And I have the login credentials. Closing this for now.
