### ISSUE TITLE
Add mechanisms to ensure photometry band names are consistent

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#144]
We want to make sure the same nomenclature is used consistently for photometry band names, eg. 2MASS_K vs 2MASS_KS. I'm not sure of the best way to enforce this.

Maybe we want to make a Photometric Bands table which has band, ucd, central wavelength.

Similarly, should the `ucd` field be required?  And could someone remind us what ucd is? :)

**Comment by kelle** [comment]
This is high priority because @ebhort27 is about to start ingest photometry. She's got JHK_MKO, WISE, and Spitzer. We need to figure out a way to standardize these band names....I'm thinking we need a look up table, right?

**Comment by Will-Cooper** [comment]
The current CMD code uses underscores for starters like Survey_Filter e.g. WISE_W1; the underscores being important for the string parsing the code does (to get things looking nice).  
But agreed, some sort of dataframe one can sort by wavelength (so we can make logical colours). Are we thinking a table with the full set from ugrizyjhk + UBV + ch1-2 + W1-4?

**Comment by kelle** [comment]
yes, exactly, a table with all the obvious ones. But we also need to think about details, like do we just use JHK for both 2MASS and MKO but use the instrument/telescope fields to differentiate? Or do we really want each band to be fully specified by the band name? I think there are some VO standards which will hopefully help us here.

**Comment by Will-Cooper** [comment]
I think either way I can code in something to ensure we only do like for like colours (e.g. J - W1 being two different colours, one 2MASS one MKO), as I don't think it's 'valid' to combine what are technically different filters in one plot?

**Comment by kelle** [comment]
Use a combo of UCD identifiers and SVO Filter ids.
- http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=browse&gname=Spitzer&asttype=
- https://www.ivoa.net/documents/UCD1+/20200212/PEN-UCDlist-1.4-20200212.html#tth_sEcB

**Comment by kelle** [comment]
Filter/Band table should have bandid, effective wavelength and width from the SVO.
