### ISSUE TITLE
Make SIMPLE schema pip installable

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#147]
To address pathing issues when running scripts, we should make the simple directory a python installable package. This would contain a single module only: `simple.schema` which should just be the schema and can be installed via `pip install -e .` at the top level directory (the `-e` is editable mode so that updates are ideally captured without requiring re-running pip). 
Care will need to be taken not to install any of the other folders as this is not a full python package.

This will mean we don't need to edit `sys.path` to find the schema when rebuilding the database.

**Comment by kelle** [comment]
This comment is superceded by #372 .
