### ISSUE TITLE
Make automated scripts to ingest survey photometry data

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#150]
We could make utility scripts to assist ingestion of survey data.  Use SIMBAD to get the survey identifier names since they've already done the matches.

Surveys which are likely included.
- [x] 2MASS
- [ ] WISE
- [x] Gaia

Start with Gaia since it also has 2MASS and WISE data if they exist.

**Comment by kelle** [comment]
It might be the should-be-prepping-my-class procrastination, but I'm gonna go ahead and get started on this.

**Comment by kelle** [comment]
Anybody have thoughts on the best way to ingest 2MASS data?  So far, I found that SIMBAD was the easiest because it's the only `astroquery` service that does a bulk identifier match. (I would have to query Vizier once per source and for IRSA, I'd have to do a coordinate search.)

**Comment by cfontanive** [comment]
> Anybody have thoughts on the best way to ingest 2MASS data? So far, I found that SIMBAD was the easiest because it's the only `astroquery` service that does a bulk identifier match. (I would have to query Vizier once per source and for IRSA, I'd have to do a coordinate search.)

Yes, I started looking into this and came to the same conclusion. Any source that has 2MASS data should be in SIMBAD anyway so I don't think that will be an issue.

**Comment by kelle** [comment]
opening new issue for WISE
