### ISSUE TITLE
Github Action to update binary repo

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#163]
Looks like this is still not automatically working, at least for @ebhort27; it doth however still work with a manual action?  
Related, in the long term this would be a good thing to trigger a rebuild of the website at the same time (it does right now anyway, but only because the website goes down after ~35mins of inactivity).

**Comment by dr-rodriguez** [comment]
I've debugged this a little and the only thing I can see is a github redirect warning. I opened a ticket in the action repo to see if they have any more insight into this: https://github.com/dmnemec/copy_file_to_another_repo_action/issues/32

**Comment by dr-rodriguez** [comment]
Just saw this in our Settings page: `Secrets are not passed to workflows that are triggered by a pull request from a fork.`

That means that the authorization token that allows it to write to SIMPLE-binary is not passed to the action and that may be why it's failing only on pull requests. This would be a limitation of github itself and we would have to figure out a way to work around it.

**Comment by kelle** [comment]
close?

**Comment by Will-Cooper** [comment]
Close if the next PR request triggers successfully I guess
