### ISSUE TITLE
Getting started with the code on your local machine

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#17]
In order to get started working with SIMPLE and [astrodbkit2](https://github.com/dr-rodriguez/AstrodbKit2) on your local machine, you should fork and clone both repos.

1) fork the repo to your personal account (click the fork button) 
2) clone your fork of the repo to your local machine

More details here:
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

At the end of the day, when you type `git remote -v`
you should have an `origin` which points to your fork and an `upstream` which points back here. 
We can discuss how to add changes to the code another day. :) 

If you have any trouble, post here.

**Comment by Will-Cooper** [comment]
origin	git@github.com:Will-Cooper/SIMPLE.git (fetch)
origin	git@github.com:Will-Cooper/SIMPLE.git (push)
upstream	git@github.com:kelle/SIMPLE.git (fetch)
upstream	git@github.com:kelle/SIMPLE.git (push)

Looks good to me

**Comment by kelle** [comment]
merging with issue to document  data ingest workflow. #11
