### ISSUE TITLE
Author Codes

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#171]
For the author codes published in the same year, we should have some consistent way to a) make sure data contributors align the same paper (e.g. not just "I reference it as Burg05b, so I'll link it to the Burg05b in the SIMPLE database" even if that's not correct and b) something easy to check and look at.

I propose appending with perhaps the last two or three digits of the DOI, so very quick to cross check.

**Comment by kelle** [comment]
I think this is a great idea. This is very related to #122 on updating publications.

**Comment by kelle** [comment]
I used the first four letters of the first author's last name, two digit year, a period, and then 2-4 digits of the end of the bibcode. E.g., Cruz10.1234.

**Comment by kelle** [comment]
This should be added to the Publications table documentation.
