### ISSUE TITLE
Simbad resolve name

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#172]
With the latest PR (for Best2020 sources) there are ~450 sources without Simbad resolvable names. The test in test_integrity.py check just the primary name, perhaps they can/should be modified to only return a message if any name doesn't match and not just the primary key?

**Comment by kelle** [comment]
- We should also think about our "policy" regarding the primary name be Simbad resolvable. Are we ok with the Simbad name just being in the Names table or do we want the primary name to always be Simbad resolvable if it's in Simbad.
- I am pretty sure some of the primary names which are not resolving do indeed have Simbad names....so there's some work to do there.

**Comment by Ajb2307** [comment]
NLTT 1011B is an example of an unresolvable name. I added an SIMBAD resolvable name to names table in #385

**Comment by Ajb2307** [comment]
One possible option to maintain SIMBAD resolvable names without changing source names would be to modify/start with the find_survey_name_in_simbad function in ingest_utils to ingest the names in SIMBAD to the names table so all names in SIMBAD are at least available in other_names column
