### ISSUE TITLE
float64 vs float32 for data ingestion

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#186]
I'm working on ingesting the Gaia data (#183 ). I am working with the proper motion data and noticed that we seem to be keeping track of way too many decimal places given the precision of the measurements. For example,
```
proper motion ra = -1068.1292486050681
proper motion ra error = 0.19892110247737055
```
If I convert to float32  (using `.astype('float32')`) , it changes to much more reasonable numbers:
```
proper motion ra = -1068.1293
proper motion ra error = 0.1989211
```

Should we convert measurements to float32 before ingesting (where appropriate) am I overthinking this?  @dr-rodriguez ? @blackwer ?

**Comment by blackwer** [comment]
SQLite still uses float64 internally, so you won't save any space. If you want to have the representation be nicer, I'd save that for when you actually display it. This won't hurt anything, but it is an extra layer. I'm inclined to not worry too much about this kind of thing, but I don't think it'd hurt either.

**Comment by dr-rodriguez** [comment]
Yea, I wouldn't worry too much. 
We could alter the astrodbkit2 json writer to coerce floats to float32, but I'd prefer not to since sometimes you *do* need float64.
