### ISSUE TITLE
Provide sample duplication script

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#20]
As sources are ingested, there is a possibility that we end up with duplicated sources. We should write a sample script that examines the database and identifies potential duplicates. This can also fold into our integrity tests.

**Comment by kelle** [comment]
Is this addressed by the tests in #36 ?

**Comment by dr-rodriguez** [comment]
We need a more complex test. 
What I'd like to do is go through every source, gather alternate designations for each, and then check against other_names in the Names table to verify that indeed we don't list the same source twice under different designations.

I have an idea (https://github.com/dr-rodriguez/SIMPLE/commit/e12a099e4aae41c3a293dcd4550b84e9fd2b4508), though a brief check showed that it times out against Simbad (too many queries).

**Comment by kelle** [comment]
I implemented this in the sort_sources function in útils.
