### ISSUE TITLE
Standardize spectra files?

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#212]
As we ingest spectra, and work towards having them all load as Spectrum1D objects, maybe we want to write them out as something different than the file we currently have (e.g., an IDL or IRAF generated FITS file).  What is that something?  A FITS file generated with `Spectrum1d.write` or something different?

**Comment by kelle** [comment]
Based on some useful info from Derek Homeier and Nick Earl, I'm thinking we should use the Spectrum1D object saved in `wcs1d-fits` format.  This will enable us to have a header and fully defined dispersion axis. https://specutils.readthedocs.io/en/stable/spectrum1d.html#providing-a-fits-style-wcs

I might need some help figuring out how to go from a wavelength array to a fits style WCS.

Also, I'm thinking we'll want a new field for this. I think we should have a link to the "original", author provided spectrum and another link to a spectrum which can be read by `specutils`.

**Comment by kelle** [comment]
new column = `original_spectrum`
in most cases, `original_spectrum` will be null. only put file name if we generate a new spectrum.
GOAL:  all files in `spectrum` column be readable by `specutils`.

**Comment by kelle** [comment]
When we write new spectra files, we will write them as `tabular-fits` format and include meta/header data is the `.meta` attribute, using ObsCore keywords for new data and preserving any pre-existing headers in whatever format it was made.

**Comment by Will-Cooper** [comment]
As discussed, this is perhaps a wider ```astropy```-standard issue?

**Comment by kelle** [comment]
- I had a chat with the maintainers of `specutils` and I will work on improving the documentation for writing spectra files. I think it already does everything we need, it's just not documented well.
- Best format is still FITS. It's the most versatile.
- Header keywords should come from [FITS standard dictionary](https://heasarc.gsfc.nasa.gov/docs/fcg/standard_dict.html
).

**Comment by kelle** [comment]
Lots of progress on this in PR #276

**Comment by kelle** [comment]
This is all in progress.
