### ISSUE TITLE
Make Modeled/Derived Parameter Table

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#244]
Make a long table for derived and modeled parameters. first ingest can be the distances from Bailer Jones 2021 (#243 ).
Columns:
- Source
- Parameter - constrained name space.
- Value
- Low value
- High value
- maximum likelihood 
- mean marginalized posterior
- variance of marginalized posterior
- Comment - could include what "value", "low", and "high" correspond to.
- Reference

**Comment by Will-Cooper** [comment]
Discussed making separate tables for mass and distance

**Comment by kelle** [comment]
Let's just start with source, parameter, value, and reference and 6 parameters: Mass, Radius, Logg, T_eff, Z (metallicity), C/O.

**Comment by kelle** [comment]
Table Name: `modeled parameters`
