### ISSUE TITLE
Ingest IRS spectra

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#257]
116 Spitzer IRS spectra from Genaro. (Is this what Jackie wants the High school students to ingest?)

Suárez and Metchev 2022 MNRAS 513, 5701

**Comment by kelle** [comment]
I think progress has been made on this. @SherelynA ?

**Comment by jel2227** [comment]
[Suarez2022.zip](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9428064/Suarez2022.zip)

**Comment by kelle** [comment]
In progress in #278 .
