### ISSUE TITLE
Ingest Wise 1810-1010, metal poor T dwarf

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#258]
Discovered by Schneider at Al 2020

![image](https://user-images.githubusercontent.com/1444249/177726510-bd1cf9dd-702a-4990-b3c8-619c09cd1d6c.jpeg)

**Comment by kelle** [comment]
@Nlodieu

**Comment by kelle** [comment]
SIMBAD: https://simbad.cds.unistra.fr/simbad/sim-id?Ident=%4015329501&Name=CWISEP%20J181006.00-101001.1&submit=submit

Discovery Paper: https://ui.adsabs.harvard.edu/abs/2020ApJ...898...77S/abstract

Parallax paper: https://ui.adsabs.harvard.edu/abs/2022A%26A...663A..84L/abstract

**Comment by kelle** [comment]
Take a look at Table 6: https://www.aanda.org/articles/aa/full_html/2022/07/aa43516-22/T6.html

We could also ingest proper motion and the modeled parameters: gravity, metallicity, radio, and mass. For the modeled parameters, there is no helper ingest function so we'll need to do it by hand.

**Comment by LishaRamon** [comment]
Haven't pushed new code because I was not able to resolve the bug/make it work. The one here has the least bugs in it, other code didn't even allow the script to run at all.

**Comment by kelle** [comment]
I want you to push the code so I can help make it work

**Comment by kelle** [comment]
New issue for the spectra convert and ingest: #434
