### ISSUE TITLE
Add Spectra table

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#26]
We need a table to store spectra. No current prototype exist. While ObsCore is a possibility, I'd recommend we avoid that for now and if necessary in the long run create a view that satisfies that.

**Comment by Will-Cooper** [comment]
What keys etc do we want to be required in a spectra header? Only allow .fits or .txt or .csv?

**Comment by kelle** [comment]
I don't think we want to be too picky here about the spectra files themselves. I want to err on the side of making as much data available/public as possible. 

I think what we absolutely need to require are the fields in the spectra table. E.g., observation date, telescope, instrument, instrument setting (e.g., Spex Prism vs SXD mode), etc.

As long as that info is in the database, I'm not as concerned about it being in the header of the file itself.

The requirement for the spectra files I think needs to be something like: it can be successfully loaded by astropy/specutils.

**Comment by kelle** [comment]
We will want Astrodbkit2 to load all the spectra as spectrum1D objects: https://specutils.readthedocs.io/en/stable/spectrum1d.html

**Comment by dr-rodriguez** [comment]
See https://github.com/dr-rodriguez/AstrodbKit2/issues/17 to track how to implement this in v0.2 of Astrodbkit2

**Comment by dr-rodriguez** [comment]
In addition to an online hosted spectra, we will want a local copy. This will require an environment variable to specify the spectra_data directory and may require some work in the AstrodbKit2 codebase.

**Comment by kelle** [comment]
I see that in the BDNYC database we constrained Instruments and Modes with a dedicated table. Do we want to do that or maybe use an enumeration, the same way we constrain spectral regime in the spectral type table?

**Comment by dr-rodriguez** [comment]
That's already in place and constrained via foreign keys; this is how it's set in the Spectra table:
```
# Foreign key constraints for telescope, instrument, mode; all handled via reference to Modes table
__table_args__ = (ForeignKeyConstraint([telescope, instrument, mode],
                                       [Modes.telescope, Modes.instrument, Modes.name],
                                       onupdate="cascade"),
                  {})
```

**Comment by kelle** [comment]
Excellent— not sure how I missed that when I reviewed the PR! But glad it’s there. I think this issue can be closed.
