### ISSUE TITLE
Release Number

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#263]
Create a release number and micro releases for each version of the database to be passed to the website (https://github.com/SIMPLE-AstroDB/SIMPLE-web/issues/98)

**Comment by kelle** [comment]
Proposed current workflow:
- Add Versions table 
- Update versions table before making a new Github release
- Release on Github

**Comment by kelle** [comment]
Referring to https://calver.org/, we've decided to version control `YYYY.minor`. E.g., the first releases in 2022 would be 2022.1, the next one would be 2022.2 and so on. We can have as many releases in a year as we want.

**Comment by kelle** [comment]
The un-released version is called `latest` and doesn't get a version number until it is released.
