### ISSUE TITLE
Coordinate transform script

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#264]
We should make a "helper" script which takes the coordinates from the Sources table and uses whatever astrometry (proper motion) to transform coordinates to a specific date.

**Comment by Will-Cooper** [comment]
```python
rashifted = ra + pmra / 1000 / 3600 * years # pmra in mas
decshifted = dec + pmdec / 1000 / 3600 * years  # pmdec in mas
```
n.b. pmra from gaia contains the cosdec term

**Comment by kelle** [comment]
I would use astropy.
- see Evolving coordinate positions between epochs: [Part 3: Coordinates Tutorial](https://learn.astropy.org/tutorials/3-Coordinates-Velocities.html)
- [apply_space_motion()](https://docs.astropy.org/en/stable/coordinates/apply_space_motion.html)

**Comment by kelle** [comment]
moved to https://github.com/astrodbtoolkit/astrodb_scripts/issues/30
