### ISSUE TITLE
Ingest all data for 2MASS J12560183-1257276

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#272]
- Xshooter Gauz15 (#284)
- SDSS iz
- WISE W1,W2,W3
- VISTA JHKY
- Gaia Parallax from 2MASS J12560215-1257217

**Comment by SherelynA** [comment]
photometry : 

SDSS.i, 22.494, 0.315
SDSS.z, 20.095, 0.090
WISE.W1, 13.6, 0.5
WISE.W2, 12.8, 0.5
WISE.W3, 11.8

**Comment by SherelynA** [comment]
Vista Photometry: 
Vista J,17.136,0.020
Vista H,15.777,0.015
Vista K,14.665,0.010
Gaia Parallax:
47.2733*u.mas, 0.4741*u.mas

**Comment by kelle** [comment]
All photometry is here and should be referenced to this paper: 
[Gauza2015_VHS1256.pdf](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9586755/Gauza2015_VHS1256.pdf)

**Comment by kelle** [comment]
closed by #296
