### ISSUE TITLE
VHS 1256 b spectral data ingest 

### ISSUE THREAD

**Issue by NiallWhiteford** [SIMPLE-AstroDB/SIMPLE-db#284]
Ingesting VHS 1256 b spectral data...

JHK band data from Gauza+2015, L band data from Miles+2018.

[vhs1256b_spectra_Figure8_Gauza2015.txt](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9455987/vhs1256b_spectra_Figure8_Gauza2015.txt)
[vhs1256b_spectra_Figure8_Miles2018.txt](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9455988/vhs1256b_spectra_Figure8_Miles2018.txt)

**Comment by kelle** [comment]
Also:
- 2MASS photometry
- other name: VHS 1256b

**Comment by NiallWhiteford** [comment]
This is the data from Gauza+2015. No calibration and just normalised. 

[vhs1256b_optnir_werrors.txt](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/9456261/vhs1256b_optnir_werrors.txt)

**Comment by kelle** [comment]
#285 just has photometry, no spectroscopy yet!

**Comment by kelle** [comment]
Progress on this in #276.

One issue is that the NIRSPEC spectrum from Miles2018 has a bunch of crappy data in it and really should have been trimmed. I'm having a hard time ingesting the noise and want to trim it in our converted version. What do other people think?

**Comment by kelle** [comment]
Closed by #296
