### ISSUE TITLE
Problem with Spectra from Manja16 Ingest

### ISSUE THREAD

**Issue by SherelynA** [SIMPLE-AstroDB/SIMPLE-db#289]
I have been trying to add a spectrum from the Manja16 ingest for the object  SIMP J0136+09 to an sed however sedwithsimple is unable to parse the spectrum: https://bdnyc.s3.amazonaws.com/xshooter/IPMS0136_total.fits. It looks like this when I used 
<img width="1210" alt="Screen Shot 2022-09-18 at 3 46 39 PM" src="https://user-images.githubusercontent.com/80668767/190925636-54d98b89-3ac6-49aa-847f-979bfb2e458a.png">. This is the message that shows up for both the optical and nir entry. I tried to use specutils to make the file into a spectrum1D object and then just manually provide it to sed however when I try to do so, the wavelength of the object is just [1.,2.,3.] Angstroms as shown :
<img width="1155" alt="Screen Shot 2022-09-18 at 4 09 31 PM" src="https://user-images.githubusercontent.com/80668767/190926398-fd17aa61-cc18-406e-b1dc-3a550b8a97b8.png">, so when I try to add it after using s.add_spectrum(), I received a message that the length of the given wavelength and flux are not the same. Is there another way to add this spectrum?

**Comment by kelle** [comment]
try `format = 'tabular-fits'` instead of `wcs1d-fits`

**Comment by SherelynA** [comment]
I tried that too and I get a list index out of range error:
<img width="1155" alt="Screen Shot 2022-09-18 at 4 18 21 PM" src="https://user-images.githubusercontent.com/80668767/190926674-dfef7f00-7ff3-4db7-9dff-c026659a9f84.png">
<img width="1155" alt="Screen Shot 2022-09-18 at 4 18 38 PM" src="https://user-images.githubusercontent.com/80668767/190926689-fb295858-1f0c-4a52-8d02-ee685ba3706d.png">
@kelle

**Comment by kelle** [comment]
what about 'iraf' ?

**Comment by SherelynA** [comment]
I got an error with that too

**Comment by kelle** [comment]
In that case, I think you'll need to read in the file with fits.open and make the Spectrum1D object by hand. We can discuss at coworking tomorrow. I can make it 3-4pm and I'll be at Hunter

**Comment by kelle** [comment]
From looking at the paper, I think the units are nanometers and erg/cm^2/s/nm.
