### ISSUE TITLE
Modify github action to push RELEASED database to SIMPLE-binary

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#290]
Current github action (gen-db.yml) pushes the latest build of the database. we want to modify that action so it only pushes the latest RELEASED version.

**Comment by Will-Cooper** [comment]
https://stackoverflow.com/questions/58475748/github-actions-how-to-check-if-current-push-has-new-tag-is-new-release

**Comment by kelle** [comment]
Should be straightforward to use `on: release` instead of `on: push`. 

See the docs for `on: release` here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
