### ISSUE TITLE
Tweak PhotometryFilters table

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#293]
Right now, we require Telescope and Instrument in the PhotometryFilters Table but I think that's redudant since those fields should be associated with a particular observation. For example, lots of different instrument/telescope combos use the SDSS filter set.  I think we should remove those columns from the PhotometryFilters table and only require `band`.

**Comment by kelle** [comment]
Also seems like if we're gonna keep UCDs, they should be in the Photometry Filters table and not in the Photometry table.

**Comment by kelle** [comment]
Ok, so, the official filter names from the SVO usually include the specific instrument name so there's not a lot of duplicate use of filter names. This tells me that using the UCD (e.g., em.opt.J) is useful so that you can run a query to get all the J-band data without needing to know all the various names for J band filters. (e.g, 2MASS.J, WFCAM.J, VISTA.J, UKIDSS.J).

Having instrument and telescope on both the Photometry and PhotometryFilters table is still redundant. But I'm not sure which table to keep it on.

**Comment by kelle** [comment]
We're leaning towards removing Telescope and Instrument from PhotometryFilters.

**Comment by kelle** [comment]
But we want to keep UCD (e.g., em.J) in the PhotometryFilters table so that we can generate J-K plots, for example, which include lots of different J filters (MKO.J and 2MASS.J). 

Also want to keep `effective_wavelength`, but it doesn't need to be perfectly accurate.

**Comment by Will-Cooper** [comment]
The website uses effective wavelength to construct colours to ensure all are blue - red
```python
if photfilters.at['effective_wavelength', bandtrue] >= \
                    photfilters.at['effective_wavelength', nextbandtrue]:  # if not blue-red
                continue
```

**Comment by Will-Cooper** [comment]
Can connect an approximate central wavelength in the PhotometryFilters table to allow this grouping of bands

**Comment by kelle** [comment]
- Remove `instrument` from Photometry table
- Remove `instrument` and `telescope` from PhotometryFilters

**Comment by kelle** [comment]
- Remove `ucd` from Photometry
- Add `ucd` to PhotometryFilters
