### ISSUE TITLE
Invalid spectral types

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#299]
The spectral_type_string in the database is meant to be 10 characters, however, some entries (eg, WISEA J130729.56-055815.4) contain values like `L8 (sl. blue)` which are invalid. While SQLite is lazy about enforcing character restrictions (among other things), other database architectures like Postgres fail. We need to either expand the field to hold more characters, or move the `(sl. blue)` part to the comment field.

**Comment by kelle** [comment]
Done in #539 .
