### ISSUE TITLE
Photometry improvements

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#301]
- add more UCDs to the Photometry table, 
- figure out the actual filters used for the Johnsons-Cousins.UBVRI and MKO.YJHK measurements.
- make a test which checks if filters are in the SVO format using their API: http://svo2.cab.inta-csic.es/svo/theory/fps3/index.php?mode=voservice

**Comment by Will-Cooper** [comment]
Links with https://github.com/SIMPLE-AstroDB/SIMPLE-web/issues/102. I note also we need UCDs in the Photometry table for SDSS, GAIA.g and WISE (as important examples)

**Comment by kelle** [comment]
Relevat to #379

**Comment by kelle** [comment]
Need to assign consistent UCDs.  For example, right now, Y band is both NIR and I.  (Sort the PhotometryFilters table by effective_wavelength.)

**Comment by kelle** [comment]
Helper functions to avoid this situation in the future are in https://github.com/astrodbtoolkit/astrodb_scripts/pull/26 with the implementation of the `ingest_photometery_filters` , `fetch_svo` functions. 

But our PhotometryFilters table probably still needs some cleanup...
