### ISSUE TITLE
Convert some FITS-like .txt files

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#308]
Lots of unreadable .txt spectra seem to be in the same format as https://bdnyc.s3.amazonaws.com/BRI+0021-0214.txt.  

Make a conversion script that works for this file and then we can try to convert a whole bunch using that script.

**Comment by kelle** [comment]
Looks like it's a lot of Spitzer data.

**Comment by kelle** [comment]
Jolie found 23 Spitzer IRS data that can be converted. In progress in #314.

**Comment by jolielheureux** [comment]
25 Converted Spitzer IRS data : 
[Archive.zip](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/10170392/Archive.zip)

**Comment by jolielheureux** [comment]
25 Converted Spitzer IRS data and pngs:
[Archive 2.zip](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/10240036/Archive.2.zip)

**Comment by kelle** [comment]
@jolielheureux , Could you also upload here the table corresponding to these sources with new spectra files? I think it's called this: `not_working_txt_table_2022-12-16.dat`

**Comment by kelle** [comment]
23 spectra uploaded to https://bdnyc.s3.amazonaws.com/IRS/. So they have URLs like this: https://bdnyc.s3.amazonaws.com/IRS/2MASSJ23515044-2537367.fits

Next step is to update the database with these files.

**Comment by kelle** [comment]
This was done but there are some problems as described in #347
