### ISSUE TITLE
Normalized fluxes or absolute flux calibration

### ISSUE THREAD

**Issue by suarezgenaro** [SIMPLE-AstroDB/SIMPLE-db#315]
Be sure data headers indicate the correct units or, in some cases, say if the spectrum is normalized (as many SpeX spectra on [SPLAT](https://splat.physics.ucsd.edu/splat/)) together with a label about if flux is in F_lambda or F_nu units.

**Comment by kelle** [comment]
Yes, this is generally part of the process of ingesting and converting spectra.
