### ISSUE TITLE
Remove Units Column from Spectra table

### ISSUE THREAD

**Issue by SherelynA** [SIMPLE-AstroDB/SIMPLE-db#324]
The original files for Suarez22 are in Janksy's and the converted files are in ergs/... Should we just get rid of the units column so this doesn't happen again, where we have mismatching units?

**Comment by kelle** [comment]
Also thinking about removing wavelength_order. We aren't actually using it for anything. But it could be useful from some higher-res spectrographs. Thoughts?

**Comment by kelle** [comment]
We discussed and decided we also don't need to keep `wavelength_order`
