### ISSUE TITLE
Units are resolvable by astropy

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#325]
We want units in the Modeled Parameters table to be resolvable by the [astropy.units module](https://docs.astropy.org/en/stable/api/astropy.units.Unit.html#astropy.units.Unit).

**Comment by Ajb2307** [comment]
Hi, I want to start working on this. I see it's labeled as tests. Is that where you want to script for this?

**Comment by kelle** [comment]
The test should go in the `tests/test_integrity.py` module.  It should actually be very similar to the test already in `test_spectra` function starting on line 469 of that file. You can use that as a guide to help get started. 

One challenge is that there is no data in the modeled parameters table yet so it will be hard to see if the test is working but I'm all in favor of having the test in place before we start adding data!

**Comment by Ajb2307** [comment]
Im going to ingest test parameters from Table 9 of Filippazzo 
https://ui.adsabs.harvard.edu/abs/2015ApJ...810..158F/abstract
To test code I've written
