### ISSUE TITLE
Ingest Filippazzo 2015 modeled parameters

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#339]
Table 9 of Filippazzo has a bunch of modeled parameters which could be ingested into the new modeled parameter table.
https://ui.adsabs.harvard.edu/abs/2015ApJ...810..158F/abstract

**Comment by kelle** [comment]
We should discuss also adding age to this ingest.

**Comment by Ajb2307** [comment]
Age would be easy to add in my current code, but the format is a range ex: "0.500-10.00". Also, it is not listed in Parameters as of right now so it would have to be added
