### ISSUE TITLE
Handle SQLAlchemy 2.0 failures

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#341]
Currently all tests are failing due to an update to SQL Alchemy to v2. @dr-rodriguez is going to investigate how to make `astrodbkit` work with this new version. Otherwise we may need to pin to a v1 of `sqlalchemy`.

**Comment by dr-rodriguez** [comment]
I've made a release of Astrodbkit2 that pins the sqlalchemy version to be less than 2.0. This is now used as part of our tests so we should be good until we can make the full switch. 
The migration to 2.0 is looking quite complicated so it will take me a few weeks to fully work out.

**Comment by kelle** [comment]
I re-ran the test on an open PR and they are passing -- Woot!  I am happy with this short term fix.
