### ISSUE TITLE
Ingest the Backyard Worlds Benchmarks

### ISSUE THREAD

**Issue by rothermichaustin** [SIMPLE-AstroDB/SIMPLE-db#428]
Here is the CSV file for the sources in my submitted BYW benchmarks paper.
[Austin-BYW-Benchmark-Sources - Sheet1.csv](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/13602111/Austin-BYW-Benchmark-Sources.-.Sheet1.csv)

**Comment by rothermichaustin** [comment]
And here is the link to the google sheet: https://docs.google.com/spreadsheets/d/1JFa8F4Ngzp3qAW8NOBurkz4bMKo9zXYeF6N1vMtqDZs/edit?usp=sharing

**Comment by kelle** [comment]
Sweet! None of these are in SIMBAD yet, right? But these are their official catwise designations?  Are there other catwise sources in SIMBad that use this same designation scheme?

**Comment by kelle** [comment]
We're gonna assume this will end up being Roth24.

**Comment by rothermichaustin** [comment]
A couple of the sources have been previously identified, however I cannot remember if they were in sambaed. If they were, I used the name given in sambaed. For the rest, I used the CatWISE designations. This designation scheme has been used before with other CatWISE objects.
