### ISSUE TITLE
Figure out ParallaxView test

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#474]
Once I moved the database creation to the `conftest.py`, the ParallaxView test stopped passing. Not sure what's going on. It's skipped for the moment.

**Comment by kelle** [comment]
Also, Will asks, "what happens if parallax is 0, NULL or negative, here?"
https://github.com/SIMPLE-AstroDB/SIMPLE-db/blob/6c46a0922b49daf0a7eea120e6492a44a579564b/simple/schema.py#L280-L288

**Comment by dr-rodriguez** [comment]
> Also, Will asks, "what happens if parallax is 0, NULL or negative, here?"
> 
> https://github.com/SIMPLE-AstroDB/SIMPLE-db/blob/6c46a0922b49daf0a7eea120e6492a44a579564b/simple/schema.py#L280-L288

Parallax cannot be NULL based on our schema. I can add a schema validation check to avoid it being 0 or negative, though I remember some cases of negative parallaxes as a result of some of the way Gaia treated them.   
Regardless- note that the where constraint specifies that only parallaxes > 0 will be shown, so there is no division by zero here.
