### ISSUE TITLE
Work out pip installation instructions

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#493]
Regardless of whether SIMPLE is pip-installable, we want to work out details for how a user can install what they need with pip without needing conda.

**Comment by dr-rodriguez** [comment]
Looking at how the tests set up the environment is a good starting point, but we may want to do things like a requirements.txt file (which is similar to conda's environment.yml)

**Comment by kelle** [comment]
```
conda  create -n "simple-db" python=3.10
conda activate simple-db
pip install pytest ads matplotlib
pip install astrodbkit2
pip install git+https://github.com/astrodbtoolkit/astrodb_utils.git@main
```

**Comment by kelle** [comment]
Both summer students (Kieran and Evan) had exactly the same problem with the current conda instructions. Multiple packages were not able to be found. I added the  http://ssb.stsci.edu/astroconda channel and it didn't help.

![image](https://github.com/SIMPLE-AstroDB/SIMPLE-db/assets/1444249/8a1cd03e-5ae0-4e85-a3d2-4f97a9f3f279)

**Comment by kelle** [comment]
Lets try to get this to work: `pip install -r requirements.txt`
