### ISSUE TITLE
Ingest Spitzer photometry from the Ultracool Sheet

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#515]
part of #452 .
https://bit.ly/ultracoolsheet

Ingest the Spitzer photometry, ch1 and ch2.  Columns DN-DR.

use `astrodb_utils.ingest_photometry` function.
telescope = Spitzer
band = IRAC.I1 and IRAC.I2

**Comment by Exu-112** [comment]
How should references such as `Kirk11;Legg13` be handled? Ingest both separately? Use the oldest one?

**Comment by Exu-112** [comment]
No, there's only 1 reference allowed
