### ISSUE TITLE
tests for database content

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#52]
I would like to write tests which make sure the data is what we expect in the database.  For example, from PR #48 , we should have these number of sources per reference:

```
reference counts
--------- ------
  Reid08b     88
   Kirk11     49
   Cruz03     45
   Cruz07     37
  Gagn15b     33
   Kirk00     28
   Cruz18     17
   Kirk10     15
   Geba02     12
  Luyt79b     11
   Knap04     11
   Chiu06     11
   Mace13     10
  Luyt79a     10
   Kirk08     10
   Hawl02     10
```

Also, I would like to add a README to the `test` directory outlining the vision we have for the difference between integrity and content tests. Integrity tests should work with any type of astronomical object with the data content tests should be specific to our database and SIMPLE data.

**Comment by Will-Cooper** [comment]
Maybe relating: how do we regenerate the _SIMPLE.db_ file after updating _data/_? This also links to #46; I tried
```python
from astrodbkit2.astrodb import Database, create_database
from simple.schema import *
CONNECTION_STRING = 'sqlite:///SIMPLE.db'
create_database(CONNECTION_STRING)
db = Database(CONNECTION_STRING)
db.query(db.Sources).all()  # empty list
```
but get an empty list in the db.query as the binary file is empty?

**Comment by dr-rodriguez** [comment]
@Will-Cooper to reload/regenerate the database after updating _data/_ you would do:
```python
from astrodbkit2.astrodb import Database

connection_string = 'sqlite:///SIMPLE.db'
db = Database(connection_string)

db.load_database('data', verbose=True)
```
See also https://astrodbkit2.readthedocs.io/en/latest/#loading-the-database ;)

You only need to call create_database if you are starting without any pre-existing database.

**Comment by kelle** [comment]
We have been adding these tests to every ingest, but it’s not documented. I think I will start a new issue which is to make an Ingesting How To page in the docs.
