### ISSUE TITLE
Ingest new JWST data and derived parameters from Alej24/25 for 0415-90

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#559]
New JWST photometry and spectra from @SherelynA 's new paper. [2MASS 0415-09](https://simple-bd-archive.org/load_solo/2MASS%20J04151954-0935066)

- [ ] JWST NIRSPEC spectrum
- [ ] JWST MIRI Spectrum 
- [ ] Magellan/FIRE Spectrum

**Comment by SherelynA** [comment]
[Carolina Spectra.zip](https://github.com/user-attachments/files/17345465/Carolina.Spectra.zip)
 @canavarrete01
