### ISSUE TITLE
Generate database action broken

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#567]
The Generate database action is breaking because `__init.py__` is calling the `version.py` module created by `setuptools` which is not supposed to be in the repo. Not sure if the call to version in `init.py` should be removed.

Broken action: https://github.com/SIMPLE-AstroDB/SIMPLE-db/actions/runs/11921063937

```python
Traceback (most recent call last):
  File "/home/runner/work/SIMPLE-db/SIMPLE-db/simple/utils/generate_database.py", line 9, in <module>
    from simple.schema import REFERENCE_TABLES
  File "/home/runner/work/SIMPLE-db/SIMPLE-db/./simple/__init__.py", line 1, in <module>
    from .version import version as __version__
ModuleNotFoundError: No module named 'simple.version'

**Comment by dr-rodriguez** [comment]
The simple package just needs to be pip installed, since we specify in the new pyproject.toml that doing so creates version.py
