### ISSUE TITLE
Copy BDNYC sources to SIMPLE

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#7]
We should write an example script that goes through the BDNYC database sources and loads them into SIMPLE.
This will require some transformation and column renaming, since the schema of the two databases is different. Furthermore, SIMPLE has more stringent checks (ie, unique names, existing references) so not everything will be able to be copied over.

This would just be the *source* information, other data (photometry, spectra, etc) would be done at a later stage.

**Comment by kelle** [comment]
I vote that we try to include everything from the [v2.0.1 release of the BDNYC database](https://github.com/BDNYC/BDNYCdb/releases/tag/2.0.1) in this v1 of the SIMPLE database.

**Comment by kelle** [comment]
What sources remain to be ingested?

**Comment by kelle** [comment]
I think we can close this. If there are particular subsets of the BDNYC database to ingest, we can open new issues.
