### ISSUE TITLE
Dealing with non symmetric errors

### ISSUE THREAD

**Issue by NiallWhiteford** [SIMPLE-AstroDB/SIMPLE-db#70]
Telecon 15/09/20:

- Discussions of how to deal with non symmetric errors -> For now we will have each value with upper and lower error options.

- Discussions of how to store/include probability distribution data. We will add option to include probability sampling/tracer data when quoting model fitting results. 

- Priors for models will not be added to SIMPLE as user can consult the published paper via reference.

**Comment by kelle** [comment]
cc @eteq.

**Comment by kelle** [comment]
just to reiterate what we decided today:

- For the moment, we will give users the option to include a link to a PDF, but will not store the PDF in the database. We will treat PDFs the same way as spectra and image files. 

- We will also make columns for upper and lower uncertainties and not assume all uncertainties are symmetric.

**Comment by kelle** [comment]
Let's discuss how to store/include probability distribution data in #33.

**Comment by kelle** [comment]
The current ModeledParameters table does assume symmetric uncertainties.  Oops.

**Comment by kelle** [comment]
This has been decided and is addressed by #484
