### ISSUE TITLE
[Discussion] Support for objects which move 

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#72]
How much support do we want to provide for objects whose coordinates change on relatively short timescales? E.g., high proper motion stars, dwarf planets? 

Conclusion from discussion today was to definitely support "sidereal motion", e.g., stars with proper motion but not to support solar system objects at the moment. To support high proper motion stars, we just need more details about coordinates, proper motion info, and astropy.coordinates.

**Comment by dr-rodriguez** [comment]
Useful reference: https://docs.astropy.org/en/stable/coordinates/apply_space_motion.html

**Comment by kelle** [comment]
Moved to https://github.com/astrodbtoolkit/astrodb-template-db/issues/35
