### ISSUE TITLE
make script to ingest data from a CSV file

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#79]
Given a CSV file with column names which correspond to tables and fields, write a script which will try to ingest the data. There will likely be lots of issues, so the script should do a bunch of tests and provide useful error messages and feedback.

**Comment by dr-rodriguez** [comment]
This is related to https://github.com/dr-rodriguez/AstrodbKit2/issues/28 which aims to implement this in the core code of AstrodbKit2

**Comment by dr-rodriguez** [comment]
The latest (as yet un-released) AstrodbKit2 code now includes an `add_tabular_data` method that takes a CSV file and loads it to the specified table. It does some initial checking to verify that sources are present and relies on the database for other verifications. The CSV file column names need to match those in the database, but if there are extra columns those get ignored.

Here's how one would call it (see also https://astrodbkit2.readthedocs.io/en/latest/#adding-data):
```db.add_tabular_data('my_file.csv', table='Photometry', fmt='csv')```

**Comment by kelle** [comment]
Now need to generate an example script using the method. Script should double check the column names and other data integrity issues.

**Comment by kelle** [comment]
script in [scripts/ingests/Y_dwarf_source_ingest.py](/SIMPLE-AstroDB/SIMPLE-db/blob/main/scripts/ingests/Y_dwarf_source_ingest.py)
