### ISSUE TITLE
Ingest 2020 Best Sample

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#81]
a new sample of 348 infrared parallaxes of L0-T8 dwarfs (244 not in Gaia DR2) from UKIRT.

https://docs.google.com/spreadsheets/d/1i98ft8g5mzPp2DNno0kcz4B9nzMxdpyz5UquAVhz-U8/edit#gid=1469954551

**Comment by kilohoku** [comment]
The 348 parallaxes (and proper motions) from UKIRT can be found in the *_UKIRT columns of the UltracoolSheet (which Kelle linked to above).  Currently, that's columns DQ-DW.

I hope that UltracoolSheet can be helpful for ingesting lots of data into SIMPLE.  I would be happy to be a resource in that regard.  It has photometry, absolute astrometry (J2000 and current epoch), proper motions, parallaxes, multiplicity, spectroscopic classifications, lots of other things.

**Comment by kelle** [comment]
@ebhort27 is gonna work on this next!
- [ ] sources, discovery ref
- [ ] spectral types
- [ ] proper motions
- [ ] parallaxes

We're not planning on ingesting any of the photometry at the moment and will add Gaia, 2MASS, WISE photometry systematically as part of #140.

**Comment by kelle** [comment]
Question: @kilohoku , for objects that have a Gaia detection, is it worth our time to ingest yours and the literature proper motion and parallaxes? or should we just ingest literature astrometry if Gaia detection is NULL?

**Comment by kilohoku** [comment]
@kelle @ebhort27 If there's a Gaia parallax and proper motion, you could ignore my UKIRT measurements -- Gaia is more precise in all cases.  But there is a surprisingly large number of literature measurements that are more precise than Gaia (I count 46 of them), and at a glance those come from reliable sources (mostly Hipparcos, Sahlmann et al., Dahn et al.), so I would consider keeping the literature values.

**Comment by kelle** [comment]
@kilohoku , Regarding columns K & L, `ra_J2000_formula` and `dec_J2000_formula`: Were those positions calculated to be at specific epoch? Also 2000?

**Comment by kilohoku** [comment]
They were calculated to be at both epoch 2000.0 and equinox 2000.0.

Note that we are using the coordinates calculated and quoted by the surveys we reference (column M).  We are not calculating them ourselves.  Coordinates based on Gaia, PS1, and UKIDSS should be quite accurate.  Coordinates based on AllWISE are *not* accurate for high-proper motion objects.  This is something we intend to fix in an UltracoolSheet update.

**Comment by kelle** [comment]
Started a new issue to focus on the UKIDSS photometry. #360

**Comment by kelle** [comment]
The Best2020 sample has been ingested. 

Individual new issues can be opened for Ultracool Sheet v2.0 ingests.
