### ISSUE TITLE
Ingest Y dwarf data

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#82]
Ingest Y dwarf sources and other information. It will be a good test of the new `add_table_data`. 

- [x] sources and coords
- [x] parallaxes
- [x] proper motions
- [ ] photometry
- [x] spectral type
- [ ] test new content

**Comment by dr-rodriguez** [comment]
@cfontanive we had to do a bit of git magic, but we were able to push your Sources and Names changes via my branch. You will want to sync up with the latest changes in upstream as you continue working on other data you want to add.

**Comment by kelle** [comment]
now that the sources are ingested, I think we decided to work on spectral types next, right?

**Comment by cfontanive** [comment]
Yes, that's what I'm doing next!

**Comment by kelle** [comment]
Start thinking about what data content tests we could add for this dataset.
