### ISSUE TITLE
Ingest Gaia EDR3 Astrometry & Photometry

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#95]
For all sources which have Gaia IDs, there are vastly improved astrometrics from DR2 to EDR3. Can use the cross match table dr2_neighbourhood (don't cross match directly with source IDs from DR2 to EDR3) to find the new source IDs and then the new data. (Some sources may have vanished from DR2 to EDR3, or have different number of parameters in their solution, e.g. only ra & dec instead of ra, dec, pmra, pmdec, parallax; or vice versa).
N.B. The photometry is different as well, improved systematics and passbands are slightly different, i.e. DR2 photometry != EDR3 photometry.

**Comment by kelle** [comment]
So basically, we shouldn't ingest any DR2 data and only EDR3. Any idea when the next data release will be? If there's gonna be a DR3 this summer, ingesting EDR3 might be low priority.

**Comment by Will-Cooper** [comment]
DR3 due first half of 2022, but astrometry and photometry will be unchanged from EDR3, it only really adds RVS spectra (not relevant for cool stars) and spectra (which will be exciting for us!)

**Comment by kelle** [comment]
@Will-Cooper , Having completely forgotten about this conversation, I just did all the work to ingest DR2 data. But we haven't _actually_ ingested it yet (#183). Is it worth actually ingesting the DR2 data or should we just start with EDR3?   Given that it doesn't look like there are any DR3 designations in Simbad yet, I would use the Gaia DR2 designations from SIMBAD and then the `gaiaedr3.dr2_neighbourhood` table, as you suggest, to get the DR3 designations. Then query the `gaiaedr3.gaia_source` table to get the actual data.

(btw, I don't mind scraping the DR2 data ingest idea. Most of the code I've written can easily be modified to ingest the EDR3 data instead.) 

What do you think?

**Comment by Will-Cooper** [comment]
I don't see why not; there's actually some pretty interesting data science questions about the differences you get between DR2 & eDR3! I'd say yes, ingest both and then use the DR2 source IDs to get the nearest neighbour in eDR3 -- to save repeating the annoying crossmatch work!

**Comment by kelle** [comment]
Will the EDR3 source ids be the same as DR3? Specifically, can I use ‘Gaia DR3’ as the designation prefix?

**Comment by Will-Cooper** [comment]
I don't think so no as every release is more or less incomparable and processed separately -- I'll check though. We'll probably need a separate prefix, i.e. Gaia DR2, Gaia EDR3, Gaia DR3, etc

**Comment by Will-Cooper** [comment]
Ah okay, I was wrong -- Ricky says they won't change from eDR3 to DR3 but will do for DR4 (which we won't worry about for now!)

**Comment by kelle** [comment]
Any idea why some of the magnitude difference fields in the `dr2_neighbourhood` table are blank?  I have 14 sources which have multiple DR3 matches and need to pick which one. Most of them have a clear choice that has a very small angular distance and magnitude difference, but there are a couple which have null magnitude difference. Any insight?

**Comment by Will-Cooper** [comment]
At a guess, one of the objects being compared to not having a G band measurement in either DR2 or eDR3. Which isn't unlikely, especially for our really red sources; see the [datamodel](https://gea.esac.esa.int/archive/documentation/GEDR3/Gaia_archive/chap_datamodel/sec_dm_auxiliary_tables/ssec_dm_dr2_neighbourhood.html) if that's any help!

**Comment by kelle** [comment]
When thinking about the `adopted` column on the astrometry, should eDR3 data always be preferred over DR2? Or should I compare their uncertainties?  (With the photometry, DR2 and DR3 are actually two different bands, so we won't have to worry about it.)

**Comment by Will-Cooper** [comment]
In general, yeah, I'd say; eDR3: longer baseline so reduced uncertainty + much improved processing. There are some edge cases for example though (like I believe Luhman 16) which have astrometry only in DR2.
