### ISSUE TITLE
Write tests/requirements for the Publications table

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#98]
shortname is required, but should bibcode and/or doi be required? What about sources which are actually unreferenced or unpublished?

**Comment by Will-Cooper** [comment]
A follow up - do we **want** unpublished stuff?

**Comment by kelle** [comment]
YES, there are some cases where we would want unpublished spectra. We don't have to accept all unpublished contributions, but there are cases where we would want it. There are always "straggler" spectra/data that don't quite make it into papers for one reason or another. Sometimes it's a shit ton of data from someone's thesis which just never got published. Anyway, YES, is the answer. :)

**Comment by kelle** [comment]
- [ ] Find unused references
- [ ] Find references with no DOI and no Bibcode and no description
